# Copyright 2026 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""SandboxTemplate build engine.

Implements the SandboxTemplate pipeline: convert an OCI archive
into a Firecracker rootfs with the OpenSandbox runtime injected, optionally
boot it for validation, create a full snapshot, and package the artifacts as
OverlayBD LSMT layers. The engine shells out to focused external tools
(oci2rootfs, firecracker, e2fsprogs, overlaybd toolchain) and emits a
content-addressed manifest plus SHA256SUMS.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path

import yaml

# ---------------------------------------------------------------------------
# Template schema
# ---------------------------------------------------------------------------

FORMATS = ("ext4", "snapshot", "overlaybd")

_QUANTITY_RE = re.compile(r"^(\d+)(Gi|Mi|Ki|G|M|K)?$", re.IGNORECASE)


def parse_quantity(value: str) -> int:
    """Parse a Kubernetes-style resource quantity into an integer (bytes or
    millis). ``"4"`` → 4, ``"4000m"`` → 4, ``"8Gi"`` → 8589934592."""
    if value is None:
        raise ValueError("quantity is required")
    value = str(value).strip()
    if value.endswith("m") and not value.endswith(("Mi", "Ki", "Gi")):
        number = value[:-1]
        if number.isdigit():
            return max(1, int(number) // 1000 or 1)
    match = _QUANTITY_RE.match(value)
    if not match:
        raise ValueError(f"invalid resource quantity: {value!r}")
    number, suffix = match.groups()
    multiplier = {
        None: 1,
        "K": 1000,
        "KI": 1024,
        "M": 1000**2,
        "MI": 1024**2,
        "G": 1000**3,
        "GI": 1024**3,
    }
    return int(number) * multiplier[suffix.upper() if suffix else None]


def _default_machine() -> dict:
    return {"vcpu": "1", "memory": "2Gi"}


def _default_output() -> dict:
    return {"rootfsSize": "30Gi", "format": "ext4"}


def template_defaults() -> dict:
    """A template skeleton with documented defaults, as generated by
    ``osb template init``."""
    return {
        "apiVersion": "sandbox.opensandbox.io/v1alpha1",
        "kind": "SandboxTemplate",
        "metadata": {"name": "example-sandbox"},
        "spec": {
            "image": "registry.example.com/sandbox:v1.0.0",
            "entrypoint": ["tail", "-f", "/dev/null"],
            "execd": "registry.example.com/execd:v1.0.0",
            "kernel": "vmlinux-6.1.177",
            "machine": _default_machine(),
            "init": "/usr/local/sbin/guest-init",
            "envs": [{"name": "EXAMPLE", "value": "1"}],
            "readiness": {"probe": "tcp://127.0.0.1:44772", "warmupSeconds": 60, "healthCheck": ""},
            "output": _default_output(),
        },
    }


def validate_template(spec: dict) -> list[str]:
    """Validate a template spec and return a list of human-readable errors.
    An empty list means the template is valid."""
    errors: list[str] = []

    def require(field: str) -> str | None:
        value = spec.get(field)
        if not value:
            errors.append(f"spec.{field} is required")
        return value

    image = require("image")
    kernel = require("kernel")
    del image, kernel

    entrypoint = spec.get("entrypoint")
    if entrypoint is not None and not isinstance(entrypoint, list):
        errors.append("spec.entrypoint must be an argv list")

    machine = spec.get("machine", {})
    for quantity_field in ("vcpu", "memory"):
        raw = machine.get(quantity_field)
        if raw is None:
            continue
        try:
            parse_quantity(raw)
        except ValueError as exc:
            errors.append(f"spec.machine.{quantity_field}: {exc}")

    output = spec.get("output", {})
    fmt = output.get("format", "ext4")
    if fmt not in FORMATS:
        errors.append(f"spec.output.format must be one of {', '.join(FORMATS)}")
    rootfs_size = output.get("rootfsSize")
    if rootfs_size is not None:
        try:
            parse_quantity(rootfs_size)
        except ValueError as exc:
            errors.append(f"spec.output.rootfsSize: {exc}")

    readiness = spec.get("readiness", {})
    warmup = readiness.get("warmupSeconds")
    if warmup is not None and (not isinstance(warmup, int) or warmup < 0):
        errors.append("spec.readiness.warmupSeconds must be a non-negative integer")
    probe = readiness.get("probe")
    if probe is not None and not probe.startswith(("tcp://", "cmd://")):
        errors.append('spec.readiness.probe must start with "tcp://" or "cmd://"')

    envs = spec.get("envs")
    if envs is not None:
        if not isinstance(envs, list):
            errors.append("spec.envs must be a list")
        else:
            for index, entry in enumerate(envs):
                if not isinstance(entry, dict) or not entry.get("name"):
                    errors.append(f"spec.envs[{index}] must be an object with a name")

    prime = output.get("prime")
    if prime is not None:
        selector = prime.get("nodeSelector")
        if not isinstance(selector, dict) or not selector:
            errors.append("spec.output.prime.nodeSelector must be a non-empty map")

    return errors


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


@dataclass
class BuildResult:
    """Files produced by a build, keyed by their artifact name."""

    directory: Path
    files: dict[str, Path] = field(default_factory=dict)
    timing: dict[str, float] = field(default_factory=dict)
    restored: bool = False
    restore_iterations: int = 0
    restore_timing: dict[str, float] = field(default_factory=dict)


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_manifest(spec: dict, result: BuildResult, kernel_digest: str, source_digest: str) -> dict:
    """Assemble the content-addressed manifest schema."""
    files: dict[str, dict] = {}
    for name, path in result.files.items():
        entry: dict[str, object] = {"sha256": sha256_file(path)}
        size = path.stat().st_size
        if size:
            entry["sizeBytes"] = size
        files[name] = entry

    validation: dict[str, object] = {
        "booted": bool(result.files.get("rootfs.ext4")),
        "timing": result.timing,
    }
    if result.restored:
        validation["restored"] = True
        validation["iterations"] = result.restore_iterations
        validation["restoreTiming"] = result.restore_timing

    machine = spec.get("machine", _default_machine())
    output = spec.get("output", _default_output())
    return {
        "schemaVersion": 1,
        "sourceImage": spec.get("image", ""),
        "sourceImageDigest": source_digest or "",
        "execd": spec.get("execd", ""),
        "kernel": {"name": spec.get("kernel", ""), "digest": kernel_digest or ""},
        "machine": {"vcpu": machine.get("vcpu", "1"), "memory": machine.get("memory", "2Gi")},
        "compatibility": {
            "firecrackerVersion": _tool_version("firecracker"),
            "architecture": platform.machine(),
            "cpuModel": _cpu_model(),
            "hostKernel": platform.release(),
        },
        "entrypoint": spec.get("entrypoint") or ["tail", "-f", "/dev/null"],
        "init": spec.get("init", ""),
        "envs": spec.get("envs") or [],
        "rootfsSize": output.get("rootfsSize", "30Gi"),
        "format": output.get("format", "ext4"),
        "files": files,
        "validation": validation,
    }


def write_checksums(directory: Path, files: dict[str, Path]) -> None:
    """Write SHA256SUMS over the produced artifact files and verify it with
    the Python hasher (no external sha256sum dependency)."""
    lines = []
    for name in sorted(files):
        lines.append(f"{sha256_file(files[name])}  {name}")
    checksums = directory / "SHA256SUMS"
    checksums.write_text("\n".join(lines) + "\n", encoding="utf-8")
    for line in lines:
        digest, name = line.split("  ", 1)
        actual = sha256_file(directory / name)
        if actual != digest:
            raise RuntimeError(f"checksum mismatch for {name}: {actual} != {digest}")


def _tool_version(binary: str) -> str:
    for flag in ("--version", "-v"):
        try:
            output = subprocess.run(
                [binary, flag], capture_output=True, text=True, timeout=10
            ).stdout
            return output.strip().splitlines()[0] if output.strip() else ""
        except (OSError, subprocess.TimeoutExpired):
            continue
    return ""


def _cpu_model() -> str:
    if sys.platform != "linux":
        return ""
    try:
        with open("/proc/cpuinfo", encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("model name"):
                    return line.split(":", 1)[1].strip()
    except OSError:
        pass
    return ""


# ---------------------------------------------------------------------------
# Stage helpers
# ---------------------------------------------------------------------------


def _run(command: list[str], cwd: Path | None = None) -> None:
    """Run a stage command with combined output surfaced on failure."""
    result = subprocess.run(command, cwd=cwd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            f"command failed ({result.returncode}): {' '.join(command)}\n{result.stdout}\n{result.stderr}"
        )


def _require_tool(name: str, env_var: str, cli_flag: str | None) -> str:
    """Resolve an external tool: explicit flag, environment variable, then PATH."""
    if cli_flag:
        return cli_flag
    override = os.environ.get(env_var)
    if override:
        return override
    found = shutil.which(name)
    if not found:
        raise RuntimeError(
            f"required tool '{name}' not found on PATH; set {env_var} or pass a path flag"
        )
    return found


# ---------------------------------------------------------------------------
# Pipeline stages
# ---------------------------------------------------------------------------


def stage_convert(
    spec: dict,
    workdir: Path,
    oci_archive: Path,
    execd_dir: Path | None,
    oci2rootfs: str,
    guest_init: str,
) -> tuple[Path, str]:
    """Materialize the OCI layers into a sparse ext4 rootfs and inject the
    OpenSandbox runtime, the optional guest init, and the sandbox env."""
    rootfs = workdir / "rootfs.ext4"
    rootfs_size = parse_quantity(spec.get("output", {}).get("rootfsSize", "30Gi"))
    size_gib = max(1, rootfs_size // (1024**3))

    _run(
        [
            oci2rootfs,
            str(oci_archive),
            "--output",
            str(rootfs),
            "--size",
            f"{size_gib}G",
            "--platform",
            "linux/amd64",
        ]
    )
    _run(["e2fsck", "-fy", str(rootfs)])

    mount_point = workdir / ".rootfs-mount"
    mount_point.mkdir(exist_ok=True)
    try:
        _run(["mount", "-o", "loop", str(rootfs), str(mount_point)])
        _inject_runtime(spec, mount_point, execd_dir, guest_init)
        subprocess.run(["sync"], check=True)
    finally:
        subprocess.run(["umount", str(mount_point)], capture_output=True)
        shutil.rmtree(mount_point, ignore_errors=True)
    _run(["e2fsck", "-fn", str(rootfs)])
    return rootfs, sha256_file(rootfs)


def _inject_runtime(
    spec: dict, mount_point: Path, execd_dir: Path | None, guest_init: str
) -> None:
    """Inject execd bootstrap files, the optional guest init, and the
    sandbox environment into the mounted rootfs."""
    opt = mount_point / "opt" / "opensandbox"
    opt.mkdir(parents=True, exist_ok=True)
    if execd_dir is not None:
        for name in ("execd", "bootstrap.sh", "prepare.sh", "bwrap"):
            source = execd_dir / name
            if source.is_file():
                shutil.copy2(source, opt / name)
                os.chmod(opt / name, 0o755)

    if spec.get("init"):
        sbin = mount_point / "usr" / "local" / "sbin"
        sbin.mkdir(parents=True, exist_ok=True)
        shutil.copy2(guest_init, sbin / "sandbox-init")
        os.chmod(sbin / "sandbox-init", 0o755)

    env_file = mount_point / "etc" / "sandbox-init.env"
    lines = []
    for entry in spec.get("envs") or []:
        lines.append(f"export {entry['name']}={entry.get('value', '')!r}")
    entrypoint = spec.get("entrypoint") or ["tail", "-f", "/dev/null"]
    lines.append(f"export ENTRYPOINT={' '.join(entrypoint)!r}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(env_file, 0o600)

    hosts = mount_point / "etc" / "hosts"
    if not hosts.exists():
        hosts.write_text("127.0.0.1 localhost\n::1 localhost ip6-localhost ip6-loopback\n")


def stage_validate_boot(
    spec: dict,
    workdir: Path,
    kernel: Path,
    firecracker: str,
    api_socket: Path,
    console_log: Path,
    timeout_seconds: float,
) -> None:
    """Boot the rootfs, wait for guest readiness, and stop. This is the
    terminal validation gate for the ext4 format."""
    _run([firecracker, "--api-sock", str(api_socket)], cwd=workdir)
    _wait_for_file(api_socket, 15)

    rootfs = workdir / "rootfs.ext4"
    machine = spec.get("machine", _default_machine())
    vcpu = max(1, parse_quantity(machine.get("vcpu", "1")) // 1000 or 1)
    memory_mib = parse_quantity(machine.get("memory", "2Gi")) // (1024**2)

    boot_args = (
        "console=ttyS0 reboot=k panic=1 pci=off nomodules "
        "root=/dev/vda rw"
    )
    if spec.get("init"):
        boot_args += " init=/usr/local/sbin/sandbox-init"

    api(api_socket, "PUT", "/machine-config",
        {"vcpu_count": vcpu, "mem_size_mib": memory_mib, "smt": False})
    api(api_socket, "PUT", "/boot-source",
        {"kernel_image_path": str(kernel), "boot_args": boot_args})
    api(api_socket, "PUT", f"/drives/{'rootfs'}",
        {"drive_id": "rootfs", "path_on_host": str(rootfs),
         "is_root_device": True, "is_read_only": False})
    api(api_socket, "PUT", "/actions", {"action_type": "InstanceStart"})

    _wait_for_log(console_log, "SANDBOX_READY", timeout_seconds)
    api(api_socket, "PATCH", "/vm", {"state": "Paused"})
    api(api_socket, "PUT", "/actions", {"action_type": "SendCtrlAltDel"})


def stage_snapshot(
    spec: dict, workdir: Path, api_socket: Path, timeout_seconds: float
) -> tuple[Path, Path]:
    """Create a full snapshot from the paused VM and restore once for
    validation."""
    vmstate = workdir / "vmstate.snap"
    memory = workdir / "memory.snap"
    api(api_socket, "PUT", "/snapshot/create",
        {"snapshot_type": "Full", "snapshot_path": str(vmstate),
         "mem_file_path": str(memory)})
    api(api_socket, "PUT", "/actions", {"action_type": "FlushMetrics"})

    restore_socket = workdir / "restore.sock"
    restore_log = workdir / "restore.console.log"
    _run(["pkill", "-f", "firecracker.*sandbox-init"], cwd=workdir)
    time.sleep(0.5)
    _run(["firecracker", "--api-sock", str(restore_socket)], cwd=workdir)
    _wait_for_file(restore_socket, 15)
    api(restore_socket, "PUT", "/snapshot/load",
        {"snapshot_path": str(vmstate),
         "mem_backend": {"backend_type": "File", "backend_path": str(memory)},
         "resume_vm": True})
    _wait_for_log(restore_log, "SANDBOX_READY", timeout_seconds)
    return vmstate, memory


def stage_package(
    workdir: Path, overlaybd_import: str, rootfs: Path, memory: Path | None
) -> None:
    """Convert rootfs (and memory, for snapshot formats) into OverlayBD LSMT
    commit layers."""
    for name, source in (("rootfs", rootfs), ("memory", memory)):
        if source is None:
            continue
        destination = workdir / "overlaybd" / name
        destination.mkdir(parents=True, exist_ok=True)
        data = destination / "layer.data.tmp"
        index = destination / "layer.index.tmp"
        commit = destination / "layer.commit.tmp"
        _run([overlaybd_import, str(source), str(data), str(index), str(commit)])
        data.unlink(missing_ok=True)
        index.unlink(missing_ok=True)
        commit.rename(destination / "layer.lsmt")


# ---------------------------------------------------------------------------
# Firecracker API helpers
# ---------------------------------------------------------------------------


def api(socket: Path, method: str, path: str, body: dict | None = None) -> str:
    import urllib.error
    import urllib.request

    url = f"http://localhost{path}"
    request = urllib.request.Request(url, method=method)
    if body is not None:
        payload = json.dumps(body).encode()
        request.add_header("Content-Type", "application/json")
        request.data = payload
    try:
        with urllib.request.urlopen(request) as response:
            return response.read().decode()
    except urllib.error.HTTPError as exc:
        raise RuntimeError(
            f"firecracker API failed: {method} {path} -> {exc.code}: {exc.read().decode()}"
        ) from exc


def _wait_for_file(path: Path, timeout_seconds: float) -> None:
    deadline = time.monotonic() + timeout_seconds
    while not path.exists():
        if time.monotonic() >= deadline:
            raise RuntimeError(f"timed out waiting for {path}")
        time.sleep(0.05)


def _wait_for_log(path: Path, marker: str, timeout_seconds: float) -> None:
    deadline = time.monotonic() + timeout_seconds
    while True:
        if path.exists() and marker in path.read_text(errors="replace"):
            return
        if time.monotonic() >= deadline:
            tail = path.read_text(errors="replace")[-2000:] if path.exists() else ""
            raise RuntimeError(
                f"timed out waiting for {marker!r} in {path}\n{tail}"
            )
        time.sleep(0.1)


def load_template(path: Path) -> dict:
    """Load and normalize a template file into its spec dict."""
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("template must be a YAML object")
    spec = document.get("spec") or document
    if not isinstance(spec, dict):
        raise ValueError("template spec must be a YAML object")
    spec.setdefault("machine", _default_machine())
    spec.setdefault("output", _default_output())
    return spec
